[package]
name = "astrodon-tauri"
version = "0.1.0"
edition = "2021"

[dependencies]
deno_runtime = "0.65.0"
wry = "0.18.1"
tokio = "1.10.1"
deno_core = "0.139.0"
serde = { version = "1.0.136", features = ["derive"] }
uuid = "1.1.1"
directories = "4.0.1"
