[package]
name = "astrodon-tauri"
version = "0.1.0"
edition = "2021"

[dependencies]
deno_runtime = "0.55.0"
wry = "0.15.0"
tokio = "1.10.1"
deno_core = "0.129.0"
serde = { version = "1.0.136", features = ["derive"] }
uuid = "0.8.2"
directories = "4.0.1"
